version: "3.8"
services:
  server:
    container_name: server-leetbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./settings:/app/settings
